# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  name: TerraformInstallLatest
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  name: Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'LZ1(1)(5cc96e7f-0fbb-4109-933a-42f31f8deee8)'
    backendAzureRmResourceGroupName: 'kartikeshn-tfstate'
    backendAzureRmStorageAccountName: 'kartikeshntfstate'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  name: Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'LZ1(1)(5cc96e7f-0fbb-4109-933a-42f31f8deee8)'

- task: TerraformTaskV4@4
  name: Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'LZ1(1)(5cc96e7f-0fbb-4109-933a-42f31f8deee8)'